name: Generate Snake

on:
  schedule: # Run workflow automatically
    - cron: "0 0 * * *" # Runs at midnight UTC every day
  workflow_dispatch: # Run workflow manually

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: Platane/snk@master
        id: snake
        with:
          github_user_name: AmirMShebly
          outputs: dist/snake.svg

      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
